module.exports=
    name:"明日方舟 | 明日方舟:终末地"
    opening:"「......荒野的风，尘土里的残骸，群星下的嚎叫......红闻到了。那是狼的气味。」"
    skin_tip:"Hypergryph games"
    author:"祈梨"
    lastModified:"2026-09-16T02:45:24.823Z"
    vote:""
    sunrise:""
    sunset:""
    icon:""
    background_color:"#000000"
    color:"#000000"
    lockable:true
    isAvailable:->
        return true
    skins:
        Doctor:
            avatar:"https://s3.bmp.ovh/2026/09/14/BNwCOjJx.png"
            name:"博士"
            prize:""
        Kaltsit:
            avatar:"https://s3.bmp.ovh/2026/09/14/fzU5fuiQ.gif"
            name:"凯尔希"
            prize:""
        Kal_Esperanta:
            avatar:"https://s3.bmp.ovh/2026/09/14/wqQVFgHY.gif"
            name:"凯尔希·思衡托"
            prize:""
        Mon3tr:
            avatar:"https://s3.bmp.ovh/2026/09/14/g6QUwmta.gif"
            name:"Mon3tr"
            prize:""
        Closure:
            avatar:"https://s3.bmp.ovh/2026/09/11/FCZhEGZx.png"
            name:"可露希尔"
            prize:""
        Blaze:
            avatar:"https://s3.bmp.ovh/2026/03/15/lR3j5wgx.png"
            name:"煌"
            prize:""
        Blaze_IgSp:
            avatar:"https://s3.bmp.ovh/2026/09/11/rEXxpL2C.png"
            name:"烛煌"
            prize:""
        Logos:
            avatar:"https://s3.bmp.ovh/2026/09/11/88DjUE3o.gif"
            name:"逻各斯"
            prize:""
        Rosmontis:
            avatar:"https://s3.bmp.ovh/2026/09/14/oq2lUvC5.png"
            name:"迷迭香"
            prize:""
        Raidian:
            avatar:"https://s3.bmp.ovh/2026/09/14/UK975RME.png"
            name:"电弧"
            prize:""
        Lancet_2:
            avatar:"https://s3.bmp.ovh/2026/09/14/TPsYpv1i.png"
            name:"Lancet-2"
            prize:""
        ThermoEx:
            avatar:"https://s3.bmp.ovh/2026/09/14/3m8QQkkq.png"
            name:"Thermo-EX"
            prize:""
        Hibiscus:
            avatar:"https://s3.bmp.ovh/2026/09/11/mtV9eEqQ.png"
            name:"濯尘芙蓉"
            prize:""
        Lava:
            avatar:"https://s3.bmp.ovh/2026/09/11/285TDF7m.png"
            name:"炎狱炎熔"
            prize:""
        Kroos:
            avatar:"https://s3.bmp.ovh/2026/09/11/9uovo16F.png"
            name:"寒芒克洛丝"
            prize:""
        Violet_Orchid:
            avatar:"https://s3.bmp.ovh/2026/09/11/bo2Qrt9Q.png"
            name:"焰狐龙梓兰"
            prize:""
        Civilight_Eterna:
            avatar:"https://s3.bmp.ovh/2026/09/11/qEXONgiz.gif"
            name:"魔王"
            prize:""
        Entelechia:
            avatar:"https://s3.bmp.ovh/2026/09/16/lHQQalbx.png"
            name:"隐德来希"
            prize:""
        Ascalon:
            avatar:"https://s3.bmp.ovh/2026/09/16/5nYIlZSl.png"
            name:"阿斯卡纶"
            prize:""
        Mudrock:
            avatar:"https://s3.bmp.ovh/2026/09/14/9oRNLfv8.png"
            name:"泥岩"
            prize:""
        Surtr:
            avatar:"https://s3.bmp.ovh/2026/09/14/sKqsPaDS.gif"
            name:"史尔特尔"
            prize:""
        Ines:
            avatar:"https://s3.bmp.ovh/2026/09/14/gBoxaXAk.png"
            name:"伊内丝"
            prize:""
        Horderer:
            avatar:"https://s3.bmp.ovh/2026/09/14/yVFcnOKm.png"
            name:"赫德雷"
            prize:""
        Shining:
            avatar:"https://s3.bmp.ovh/2026/09/16/4XIA7NcC.png"
            name:"闪灵"
            prize:""
        Nightingale:
            avatar:"https://s3.bmp.ovh/2026/09/16/IOF2ryfQ.png"
            name:"夜莺"
            prize:""
        Nymph:
            avatar:"https://s3.bmp.ovh/2026/09/16/XJNe9eAf.png"
            name:"妮芙"
            prize:""
        Chen:
            avatar:"https://s3.bmp.ovh/2026/09/11/rJTj0jzE.png"
            name:"陈"
            prize:""
        Hoshiguma:
            avatar:"https://s3.bmp.ovh/2026/09/11/DY1hRDOA.gif"
            name:"斩业星熊"
            prize:""
        Swire:
            avatar:"https://s3.bmp.ovh/2026/09/11/7uXFfBFE.png"
            name:"诗怀雅"
            prize:""
        Lin:
            avatar:"https://s3.bmp.ovh/2026/09/11/6YY4netW.gif"
            name:"林"
            prize:""
        Chongyue:
            avatar:"https://s3.bmp.ovh/2026/09/11/oykreebz.gif"
            name:"重岳"
            prize:""
        Wang:
            avatar:"https://s3.bmp.ovh/2026/09/11/0yX9tD3t.gif"
            name:"望"
            prize:""
        Ling:
            avatar:"https://s3.bmp.ovh/2026/09/11/2iw2xq3I.gif"
            name:"令"
            prize:""
        Shu:
            avatar:"https://s3.bmp.ovh/2026/09/11/tPzHql1B.gif"
            name:"黍"
            prize:""
        Nian:
            avatar:"https://s3.bmp.ovh/2026/09/11/HvzVGHYc.gif"
            name:"年"
            prize:""
        Xi:
            avatar:"https://s3.bmp.ovh/2026/09/11/J7Mksh4B.gif"
            name:"夕"
            prize:""
        Yu:
            avatar:"https://s3.bmp.ovh/2026/09/14/FLLTAhrr.gif"
            name:"余"
            prize:""
        Zuole:
            avatar:"https://s3.bmp.ovh/2026/09/11/cSvGVbOQ.gif"
            name:"左乐"
            prize:""
        Leizi:
            avatar:"https://s3.bmp.ovh/2026/09/14/2fvgVnOz.png"
            name:"司霆惊蛰"
            prize:""
        Qiubai:
            avatar:"https://s3.bmp.ovh/2026/09/11/emVOXjGU.png"
            name:"仇白"
            prize:""
        Saga:
            avatar:"https://s3.bmp.ovh/2026/09/16/sNGc3wg4.png"
            name:"嵯峨"
            prize:""
        Vina:
            avatar:"https://s3.bmp.ovh/2026/09/15/eo4kwDAz.png"
            name:"维娜·维多利亚"
            prize:""
        Bagpipe:
            avatar:"https://s3.bmp.ovh/2026/09/14/bJhSS7lV.png"
            name:"风笛"
            prize:""
        Horn:
            avatar:"https://s3.bmp.ovh/2026/09/11/PdVjjnhR.png"
            name:"号角"
            prize:""
        Goldenglow:
            avatar:"https://s3.bmp.ovh/2026/09/11/k7YLzR0p.gif"
            name:"澄闪"
            prize:""
        Phantom:
            avatar:"https://s3.bmp.ovh/2026/09/14/BGNWZF3u.gif"
            name:"傀影"
            prize:""
        Tragodia:
            avatar:"https://s3.bmp.ovh/2026/09/11/p7iYXaSu.png"
            name:"酒神"
            prize:""
        Reed:
            avatar:"https://s3.bmp.ovh/2026/09/11/aWZnUGuW.gif"
            name:"焰影苇草"
            prize:""
        Necrass:
            avatar:"https://s3.bmp.ovh/2026/09/11/1P9h7VQG.gif"
            name:"死芒"
            prize:""
        Silverash:
            avatar:"https://s3.bmp.ovh/2026/09/14/OGPFiTb2.gif"
            name:"银灰"
            prize:""
        SliverAsh_RF:
            avatar:"https://s3.bmp.ovh/2026/09/14/Xpo3b2aM.png"
            name:"凛御银灰"
            prize:""
        Pramanix:
            avatar:"https://s3.bmp.ovh/2026/09/14/kELfnfPZ.png"
            name:"圣聆初雪"
            prize:""
        Gnosis:
            avatar:"https://s3.bmp.ovh/2026/09/14/xCsXc6Se.png"
            name:"灵知"
            prize:""
        Degenbrecher:
            avatar:"https://s3.bmp.ovh/2026/09/14/vHj4RlbY.png"
            name:"锏"
            prize:""
        Typhon:
            avatar:"https://s3.bmp.ovh/2026/09/16/DmwBClAX.png"
            name:"提丰"
            prize:""
        Skadi:
            avatar:"https://s3.bmp.ovh/2026/09/14/SB5HXSs8.png"
            name:"斯卡蒂"
            prize:""
        Skadi_CH:
            avatar:"https://s3.bmp.ovh/2026/09/14/mjF4DLTG.gif"
            name:"浊心斯卡蒂"
            prize:""
        Specter:
            avatar:"https://s3.bmp.ovh/2026/09/14/SZJZQ1mo.gif"
            name:"归溟幽灵鲨"
            prize:""
        Gladiia:
            avatar:"https://s3.bmp.ovh/2026/03/16/pAZiUFIu.png"
            name:"歌蕾蒂娅"
            prize:""
        Ulpianus:
            avatar:"https://s3.bmp.ovh/2026/09/14/uUWkmumX.png"
            name:"乌尔比安"
            prize:""
        Mizuki:
            avatar:"https://s3.bmp.ovh/2026/09/12/zR31lXIh.gif"
            name:"水月"
            prize:""
        Thorn:
            avatar:"https://s3.bmp.ovh/2026/09/14/J7kk2HOX.png"
            name:"棘刺"
            prize:""
        Thorn_Lodestar:
            avatar:"https://s3.bmp.ovh/2026/09/14/az8HAt5Z.gif"
            name:"引星棘刺"
            prize:""
        Elysium:
            avatar:"https://s3.bmp.ovh/2026/09/12/HUma91bG.png"
            name:"极境"
            prize:""
        Irene:
            avatar:"https://s3.bmp.ovh/2026/09/14/4u8Dybz3.png"
            name:"艾丽妮"
            prize:""
        Weedy:
            avatar:"https://s3.bmp.ovh/2026/09/14/0cKbidZy.png"
            name:"温蒂"
            prize:""
        Lumien:
            avatar:"https://s3.bmp.ovh/2026/09/16/yBtY7RrH.png"
            name:"流明"
            prize:""
        Exusiai_NC:
            avatar:"https://s3.bmp.ovh/2026/09/12/iA4GrKAc.gif"
            name:"新约能天使"
            prize:""
        Lemuan:
            avatar:"https://s3.bmp.ovh/2026/09/12/7sW6Db6c.png"
            name:"蕾缪安"
            prize:""
        Fiammetta:
            avatar:"https://s3.bmp.ovh/2026/09/12/K1df7Xxf.png"
            name:"菲亚梅塔"
            prize:""
        Mostima:
            avatar:"https://s3.bmp.ovh/2026/09/12/4zkUWdz5.png"
            name:"莫斯提马"
            prize:""
        Archetto:
            avatar:"https://s3.bmp.ovh/2026/09/16/4GxSUZ2K.png"
            name:"空弦"
            prize:""
        Sankta:
            avatar:"https://s3.bmp.ovh/2026/09/16/Ccu62GyU.png"
            name:"信仰搅拌机"
            prize:""
        Executor:
            avatar:"https://s3.bmp.ovh/2026/09/12/it4UNkGm.png"
            name:"送葬人"
            prize:""
        Virtuosa:
            avatar:"https://s3.bmp.ovh/2026/09/12/xFCi5wdH.gif"
            name:"塑心"
            prize:""
        MakotoYuki:
            avatar:"https://s3.bmp.ovh/2026/09/16/EqVW5akK.png"
            name:"结城理"
            prize:""
        Emper:
            avatar:"https://s3.bmp.ovh/2026/09/15/j4dmmce8.png"
            name:"大帝"
            prize:""
        Texas:
            avatar:"https://s3.bmp.ovh/2026/09/15/JHO3dW2U.png"
            name:"德克萨斯"
            prize:""
        Texas_Om:
            avatar:"https://s3.bmp.ovh/2026/09/12/NpJ53NMK.gif"
            name:"缄默德克萨斯"
            prize:""
        Lappland:
            avatar:"https://s3.bmp.ovh/2026/09/15/f3dZUSks.png"
            name:"拉普兰德"
            prize:""
        Lappland_De:
            avatar:"https://s3.bmp.ovh/2026/09/12/8iSx6Gd7.gif"
            name:"荒芜拉普兰德"
            prize:""
        Vigil:
            avatar:"https://s3.bmp.ovh/2026/09/11/3tan2SBJ.png"
            name:"伺夜"
            prize:""
        Bellone:
            avatar:"https://s3.bmp.ovh/2026/09/11/fBb2pdk7.png"
            name:"贝洛内"
            prize:""
        Suzuran:
            avatar:"https://s3.bmp.ovh/2026/09/12/PvDihnh4.png"
            name:"铃兰"
            prize:""
        Angelina:
            avatar:"https://s3.bmp.ovh/2026/09/12/SEI6oQP7.png"
            name:"安洁莉娜"
            prize:""
        Angelina_ALT:
            avatar:"https://s3.bmp.ovh/2026/09/15/n9MYYsVg.gif"
            name:"予愿安洁莉娜"
            prize:""
        Crownslayer:
            avatar:"https://s3.bmp.ovh/2026/09/16/Nc66Zq5H.png"
            name:"弑君者"
            prize:""
        Nearl:
            avatar:"https://s3.bmp.ovh/2026/09/12/co9bY89j.gif"
            name:"耀骑士临光"
            prize:""
        Miynar:
            avatar:"https://s3.bmp.ovh/2026/09/12/5xpxFbnw.gif"
            name:"玛恩纳"
            prize:""
        Blemshine:
            avatar:"https://s3.bmp.ovh/2026/09/16/dNImvhk9.png"
            name:"瑕光"
            prize:""
        Saria:
            avatar:"https://s3.bmp.ovh/2026/09/15/g7cJWH0m.png"
            name:"塞雷娅"
            prize:""
        Muelsyse:
            avatar:"https://s3.bmp.ovh/2026/09/12/ZKkRytHH.gif"
            name:"缪尔赛思"
            prize:""
        Silence:
            avatar:"https://s3.bmp.ovh/2026/09/12/850xBGmW.png"
            name:"淬羽赫默"
            prize:""
        Ptilopsis:
            avatar:"https://s3.bmp.ovh/2026/09/12/ThKGSq8y.png"
            name:"白面鸮"
            prize:""
        Ifrit:
            avatar:"https://s3.bmp.ovh/2026/09/12/OmseMUhm.png"
            name:"伊芙利特"
            prize:""
        Magallan:
            avatar:"https://s3.bmp.ovh/2026/09/16/PhzjyHIe.png"
            name:"麦哲伦"
            prize:""
        Dorothy:
            avatar:"https://s3.bmp.ovh/2026/09/15/rxSpeq4h.png"
            name:"多萝西"
            prize:""
        Mountain:
            avatar:"https://s3.bmp.ovh/2026/09/16/5xwpgQAM.png"
            name:"山"
            prize:""
        Hoolheyak:
            avatar:"https://s3.bmp.ovh/2026/09/16/d6Po3baJ.png"
            name:"霍尔海雅"
            prize:""
        Aphrissa:
            avatar:"https://s3.bmp.ovh/2026/09/15/XuOGclH9.png"
            name:"谬因"
            prize:""
        Eyjafjalla:
            avatar:"https://s3.bmp.ovh/2026/09/11/1Mg4yKG1.png"
            name:"艾雅法拉"
            prize:""
        Schwarz:
            avatar:"https://s3.bmp.ovh/2026/09/16/IcYDTsv3.png"
            name:"黑"
            prize:""
        Passenger:
            avatar:"https://s3.bmp.ovh/2026/09/12/Hoa8qbVz.gif"
            name:"异客"
            prize:""
        Pepe:
            avatar:"https://s3.bmp.ovh/2026/09/15/EOFeizKe.png"
            name:"佩佩"
            prize:""
        Titi:
            avatar:"https://s3.bmp.ovh/2026/09/11/8LqwNqVn.png"
            name:"缇缇"
            prize:""
        Ceobe:
            avatar:"https://s3.bmp.ovh/2026/03/16/ncG5K3rF.png"
            name:"刻俄柏"
            prize:""
        Carnelian:
            avatar:"https://s3.bmp.ovh/2026/09/16/4Jm21f7y.png"
            name:"卡涅利安"
            prize:""
        Narantuya:
            avatar:"https://s3.bmp.ovh/2026/09/16/MxPI1hO2.png"
            name:"娜仁图亚"
            prize:""
        Gavial:
            avatar:"https://s3.bmp.ovh/2026/09/15/8nFumlJt.png"
            name:"百炼嘉维尔"
            prize:""
        Eunectes:
            avatar:"https://s3.bmp.ovh/2026/09/15/YlMDGb40.png"
            name:"森蚺"
            prize:""
        Myrtle:
            avatar:"https://s3.bmp.ovh/2026/09/15/qZV16v3y.png"
            name:"桃金娘"
            prize:""
        Mantra:
            avatar:"https://s3.bmp.ovh/2026/09/16/QToheUh3.png"
            name:"真言"
            prize:""
        Lindong:
            avatar:"https://s3.bmp.ovh/2026/09/16/0x1U2xK8.png"
            name:"怒潮凛冬"
            prize:""
        Zhenli:
            avatar:"https://s3.bmp.ovh/2026/09/15/CraGURqx.png"
            name:"真理"
            prize:""
        Gumi:
            avatar:"https://s3.bmp.ovh/2026/03/16/SgAMXYPV.png"
            name:"古米"
            prize:""
        Poca:
            avatar:"https://s3.bmp.ovh/2026/09/15/D9KPWdOj.png"
            name:"早露"
            prize:""
        Hellagur:
            avatar:"https://s3.bmp.ovh/2026/09/15/wvSeKIHO.png"
            name:"赫拉格"
            prize:""
        U_official:
            avatar:"https://s3.bmp.ovh/2026/09/15/c2R9c8RW.png"
            name:"U-Official"
            prize:""
        Haruka:
            avatar:"https://s3.bmp.ovh/2026/09/15/bI8exG9P.gif"
            name:"遥"
            prize:""
        Ebenholz:
            avatar:"https://s3.bmp.ovh/2026/09/16/yvGGMwea.png"
            name:"黑键"
            prize:""
        Lessing:
            avatar:"https://s3.bmp.ovh/2026/09/16/8189d8S4.png"
            name:"止颂"
            prize:""
        Viviana:
            avatar:"https://s3.bmp.ovh/2026/09/15/rZcfXeT7.png"
            name:"薇薇安娜"
            prize:""
        Ray:
            avatar:"https://s3.bmp.ovh/2026/09/16/PPvK5OTM.png"
            name:"莱伊"
            prize:""
        Thumpy:
            avatar:"https://s3.bmp.ovh/2026/09/15/VwxR9shT.png"
            name:"珊比"
            prize:""
        Marcille:
            avatar:"https://s3.bmp.ovh/2026/09/16/6U5OCNRn.png"
            name:"玛露西尔"
            prize:""
        Sakiko:
            avatar:"https://s3.bmp.ovh/2026/09/16/bUZWIeoG.png"
            name:"丰川祥子"
            prize:""
        Endministrator_M:
            avatar:"https://s3.bmp.ovh/2026/09/15/IEZGHjmq.png"
            name:"管理员(男)"
            prize:""
        Endministrator_F:
            avatar:"https://s3.bmp.ovh/2026/09/12/jCQbQwiU.png"
            name:"管理员(女)"
            prize:""
        Perlica:
            avatar:"https://s3.bmp.ovh/2026/09/15/xe89Hv1C.png"
            name:"佩丽卡"
            prize:""
        Qianyu:
            avatar:"https://s3.bmp.ovh/2026/09/12/0VgAhKzp.png"
            name:"陈千语"
            prize:""
        Lifeng:
            avatar:"https://s3.bmp.ovh/2026/09/12/2KnSEx1f.png"
            name:"黎风"
            prize:""
        Pogranichnik:
            avatar:"https://s3.bmp.ovh/2026/09/15/eMmUyio4.png"
            name:"骏卫"
            prize:""
        Ember:
            avatar:"https://s3.bmp.ovh/2026/09/12/i9s4QUyE.png"
            name:"余烬"
            prize:""
        Last_Rite:
            avatar:"https://s3.bmp.ovh/2026/09/12/1nh3cW6V.png"
            name:"别礼"
            prize:""
        Ardelia:
            avatar:"https://s3.bmp.ovh/2026/09/12/E54sIiF4.png"
            name:"艾尔黛拉"
            prize:""
        Laevatain:
            avatar:"https://s3.bmp.ovh/2026/09/12/WNIld9YG.png"
            name:"莱万汀"
            prize:""
        Gilberta:
            avatar:"https://s3.bmp.ovh/2026/09/12/oMZh9TFF.png"
            name:"洁尔佩塔"
            prize:""
        Yvonne:
            avatar:"https://s3.bmp.ovh/2026/09/12/JhgB1heY.png"
            name:"伊冯"
            prize:""
        Tangtang:
            avatar:"https://s3.bmp.ovh/2026/09/15/ttvZgPxf.png"
            name:"汤汤"
            prize:""
        Rossi:
            avatar:"https://s3.bmp.ovh/2026/09/14/oq2lUvC5.png"
            name:"洛茜"
            prize:""
        Fangyi:
            avatar:"https://s3.bmp.ovh/2026/09/12/ydYlgqfH.png"
            name:"庄方宜"
            prize:""
        Mifu:
            avatar:"https://s3.bmp.ovh/2026/09/15/6fWI2Hwd.png"
            name:"弭弗"
            prize:""
        Camille:
            avatar:"https://s3.bmp.ovh/2026/09/15/GyeQaMee.png"
            name:"卡缪"
            prize:""
        Arcane:
            avatar:"https://s3.bmp.ovh/2026/09/15/uKwz0GJK.png"
            name:"诀"
            prize:""
        Liino:
            avatar:"https://s3.bmp.ovh/2026/09/15/gehqzCkZ.png"
            name:"梨诺"
            prize:""
        Typhoeus:
            avatar:"https://s3.bmp.ovh/2026/09/15/5RfQDGbF.png"
            name:"提弗洛斯"
            prize:""
